openapi: 3.0.0
info:
  title: Waste Reduction System API
  description: API for personalized product recommendations and dead stock risk analysis to minimize food waste
  version: 1.0.0
  contact:
    name: API Support
    email: support@wasterestoration.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.wasterestoration.com
    description: Production server

paths:
  /health:
    get:
      summary: Health Check
      description: Check the API and model status
      operationId: healthCheck
      tags:
        - System
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  model_status:
                    type: string
                    example: loaded
                  api_version:
                    type: string
                    example: 1.0.0
        '500':
          description: Service unhealthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /users:
    get:
      summary: Get Users
      description: Retrieve all available users with their dietary preferences and allergies
      operationId: getUsers
      tags:
        - Users
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /categories:
    get:
      summary: Get Categories
      description: Retrieve all available product categories
      operationId: getCategories
      tags:
        - Products
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  categories:
                    type: array
                    items:
                      type: string
                    example: ["Biscuits", "Sauces", "Meat", "Cheese", "Beverages", "Dairy", "Snacks", "Spreads"]
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /recommendations/{user_id}:
    get:
      summary: Get Personalized Recommendations
      description: Get personalized product recommendations for a specific user based on their preferences, purchase history, and dietary restrictions
      operationId: getRecommendations
      tags:
        - Recommendations
      parameters:
        - name: user_id
          in: path
          required: true
          description: The unique identifier of the user
          schema:
            type: string
            example: U0001
        - name: n
          in: query
          required: false
          description: Number of recommendations to return
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 10
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecommendationsResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /dead_stock_risk:
    get:
      summary: Get Dead Stock Risk Items
      description: Retrieve products at risk of becoming dead stock (low sales velocity, approaching expiry)
      operationId: getDeadStockRisk
      tags:
        - Products
      parameters:
        - name: category
          in: query
          required: false
          description: Filter by product category
          schema:
            type: string
            enum: ["Biscuits", "Sauces", "Meat", "Cheese", "Beverages", "Dairy", "Snacks", "Spreads"]
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeadStockRiskItem'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          description: User ID
          example: U0001
        name:
          type: string
          description: User display name
          example: User U0001
        diet_type:
          type: string
          description: Dietary preference
          enum: ["vegan", "vegetarian", "non-vegetarian", "eggs"]
          example: vegan
        allergies:
          type: string
          description: List of allergies as string
          example: "['nuts', 'dairy']"
        prefers_discount:
          type: boolean
          description: Whether user prefers discounted items
          example: true

    Recommendation:
      type: object
      properties:
        product_id:
          type: string
          description: Unique product identifier
          example: P0123
        product_name:
          type: string
          description: Product name
          example: Organic Tomato Sauce
        name:
          type: string
          description: Product name (duplicate field)
          example: Organic Tomato Sauce
        category:
          type: string
          description: Product category
          example: Sauces
        days_until_expiry:
          type: integer
          description: Days remaining until product expires
          example: 7
        price:
          type: number
          format: float
          description: Current price after discount (in rupees)
          example: 245.50
        price_mrp:
          type: number
          format: float
          description: Maximum retail price
          example: 245.50
        discount:
          type: number
          format: float
          description: Current discount percentage
          example: 30.0
        current_discount_percent:
          type: number
          format: float
          description: Current discount percentage (duplicate field)
          example: 30.0
        expiry_date:
          type: string
          format: date
          description: Product expiration date
          example: "2024-01-20"
        score:
          type: number
          format: float
          description: Recommendation score (higher is better)
          example: 8.5
        is_dead_stock_risk:
          type: integer
          description: Binary flag (1 = at risk, 0 = not at risk)
          enum: [0, 1]
          example: 1

    RecommendationsResponse:
      type: object
      properties:
        user_id:
          type: string
          description: User ID
          example: U0001
        recommendations:
          type: array
          items:
            $ref: '#/components/schemas/Recommendation'

    DeadStockRiskItem:
      type: object
      properties:
        product_id:
          type: string
          description: Unique product identifier
          example: P0015
        name:
          type: string
          description: Product name
          example: Fresh Milk
        category:
          type: string
          description: Product category
          example: Dairy
        days_until_expiry:
          type: integer
          description: Days remaining until expiry
          example: 3
        current_discount_percent:
          type: number
          format: float
          description: Current discount applied
          example: 40.0
        price_mrp:
          type: number
          format: float
          description: Maximum retail price
          example: 65.00
        expiry_date:
          type: string
          format: date
          description: Product expiration date
          example: "2024-01-16"
        risk_score:
          type: number
          format: float
          nullable: true
          description: Risk assessment score
          example: null
        threshold:
          type: integer
          nullable: true
          description: Dynamic threshold for the product
          example: null

    Error:
      type: object
      properties:
        detail:
          type: string
          description: Error message describing what went wrong
          example: Model not loaded

tags:
  - name: System
    description: System health and status endpoints
  - name: Users
    description: User management endpoints
  - name: Products
    description: Product and inventory endpoints
  - name: Recommendations
    description: Recommendation engine endpoints 